version: '3'
services:
  db:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
    ports:
      - "5432:5432"
  api:
    build: ./api
    environment:
      - ENVIRONMENT=${ENVIRONMENT:-dev}
      - USERNAME=${POSTGRES_USER:-postgres}
      - PASSWORD=${POSTGRES_PASSWORD}
    ports: 
      - "8080:8080"
    command: sh -c "./wait-for-it.sh db:5432 -- go-wrapper run --username $${USERNAME} --password $${PASSWORD}"
    depends_on:
      - db
  ui:
    build: ./ui
    environment:
      ENV: ${ENVIRONMENT:-dev}
    ports:
      - "8081:8081"
    depends_on:
      - api
      - db